# ===== LOCAL PROFILE =====

spring:
  # Postgres
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/epigraph}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  # Liquibase
  liquibase:
    change-log: classpath:db/db-changelog.yaml

  # JPA: allow Hibernate to auto-update schema in local dev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  # Google OAuth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile
          yandex:
            client-id: ${YANDEX_CLIENT_ID}
            client-secret: ${YANDEX_CLIENT_SECRET}
            scope: login:email, login:info
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/yandex"
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info?format=json
            user-name-attribute: id

app:
  base-url: http://localhost:8080
  # check user ip (hide/show login methods for different countries)
  geo:
    enabled: true
    blocked-countries: RU

  # Notification banner message
  banner:
    message: "В настоящий момент часть функционала недоступна. Ведутся технические работы."

  # Jwt Service
  jwt:
    secret: dGhpcy1pcy1hLXZlcnktc2VjcmV0LWtleS1mb3ItZXBpZ3JhcGgtYXBw
  vapid:
    public-key: ${VAPID_PUBLIC_KEY:}
    private-key: ${VAPID_PRIVATE_KEY:}
    subject: mailto:epigraph.support@icloud.com

  # Email Verification
  mail:
    from: ${MAIL_FROM:noreply@epigraph.me}
  resend:
    api-key: ${RESEND_API_KEY}

# Logging: verbose for local development
logging:
  level:
    root: INFO
    com.mkrasikoff.epigraph: DEBUG
    org.springframework.web: INFO
    org.springframework.web.servlet.DispatcherServlet: WARN
    org.springframework.web.servlet.mvc.method.annotation: WARN
    org.springframework.web.servlet.handler: WARN
    org.springframework.web.servlet.view: WARN
    liquibase: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: WARN
